global using System.Diagnostics;
global using System.Numerics;
global using PathTracer;
global using PathTracer.Core;
global using PathTracer.ImageWriters;
global using PathTracer.Platform;
global using PathTracer.Platform.GraphicsLegacy;
global using PathTracer.Platform.Inputs;
global using PathTracer.UI;